version: "3.8"

services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - SQLITE_FILENAME=/app/tutorials.db
      - PORT=8081
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
